Fix for 'Show Solutions'. Correct answers are now displayed, and chec…
LAYAIraq/LAYA-Iraq-Frontend pull request #305
Opened 2022-09-27 09:41 UTC by NVieregg

Show Solutions fixed in SCMC. Please check if:

- [ ] Correct answers are checked, wrong answers are crossed
- [ ] All correct answers are displayed below.

Note: we should consider renaming the SCMC Block. Discuss in tomorrows meeting.

2022-09-27 12:29 UTC, cmauf requested changes
Some issues in the code (see comments)

Furthermore, I think we should enforce having only one possible answer for Multiple Choice questions by using radio buttons instead of check boxes.

2022-09-27 12:29 UTC, cmauf commented on src/plugins/laya-la-scmc/view.vue
>       */
Please update the "Last Updated" Line in function comment (also for `diffSolution`)

2022-09-27 12:29 UTC, cmauf commented on src/plugins/laya-la-scmc/view.vue
>            this.showSolutions.push(this.options[i].text)
`showSolutions` is not returned in preview

2022-09-27 12:29 UTC, cmauf commented on src/plugins/laya-la-scmc/view.vue
> +          // }
these can be simplified to only contain l.314

2022-09-27 12:29 UTC, cmauf commented on src/plugins/laya-la-scmc/view.vue
>            this.showSolutions.push(this.options[i].text)
This doesn't use the simple language alternative when `courseSimple` is true

2022-09-28 12:44 UTC, NVieregg commented
> Some issues in the code (see comments)
> 
> Furthermore, I think we should enforce having only one possible answer for Multiple Choice questions by using radio buttons instead of check boxes.

I just checked, and the buttons are already of the type 'radio'?

2022-10-10 07:35 UTC, cmauf requested changes
Show icon when no answer is given

2022-10-10 07:35 UTC, cmauf commented on src/plugins/laya-la-scmc/view.vue
> +          this.eval[i] = { 'far fa-times-circle text-danger': true }
If no answer is is given, no item will be marked correct or wrong. In this case, I would suggest a cross mark at the correct answer.

2022-10-12 10:40 UTC, NVieregg commented
Simply changing the button type on "correct?" to radio does not work, no solutions are displayed and I don't know why.... We also need to add a conditional, since radio buttons should only be displayed for single choice? Will probably take longer than 5 minutes...

2022-10-12 12:52 UTC, cmauf commented
@NVieregg I added some lines, please revisit then ping me

2022-10-12 14:52 UTC, NVieregg commented
@cmauf looks really good!

2022-10-13 09:53 UTC, merged