Fix for 'Show Solutions'. Correct format is now displayed.
LAYAIraq/LAYA-Iraq-Frontend pull request #306
Opened 2022-09-27 09:58 UTC by NVieregg

Drag&Drop should now display Solutions in correct format. Please check if

- [ ] Format is now correct for Check Solution. Only Category and Answer should be displayed.
- [ ] Check if Simple Language also works the same.

Note: we should consider renaming Categories and Items. Discuss in tomorrow's meeting.

2022-09-27 12:43 UTC, cmauf reviewed
We might consider adding a warning to course authors when they did not specify a correct answer. Also applies to #305

2022-09-28 12:46 UTC, NVieregg commented
> We might consider adding a warning to course authors when they did not specify a correct answer. Also applies to #305

As we agreed on pushing the warnings into the big refactoring, please check this again, if everything is correct now and then merge. Thanks!

2022-10-10 07:30 UTC, cmauf requested changes
improve readability

2022-10-10 07:30 UTC, cmauf commented on src/plugins/laya-la-drag-drop/view.vue
> +        {{ item.label }}: {{ courseSimple? categories[items[index].category].simple: categories[items[index].category].text }}
simplify to `courseSimple? item.simple: item.text` for better readability

2022-10-12 11:38 UTC, LAYAIraq approved these changes

2022-10-12 11:45 UTC, cmauf approved these changes

2022-10-12 11:46 UTC, merged