Tli 39 multiple choice true false
LAYAIraq/LAYA-Iraq-Frontend pull request #325
Opened 2022-11-25 15:39 UTC by NVieregg

Added the possibility to choose True/False with already populated answers in Choices component.

Please check if:

- [ ] correct answers are populated
- [ ] true/false are radio buttons
- [ ] only one type is checked

2023-01-17 17:37 UTC, NVieregg commented
@cmauf new commits pushed, please check!

2023-01-20 10:48 UTC, cmauf requested changes
Modal in edit.vue doesn't work as expected, additional minor issues

2023-01-20 10:48 UTC, cmauf commented on src/plugins/laya-la-scmc/edit.vue
> +      static-change-tf
this property has to be just `static`

2023-01-20 10:48 UTC, cmauf commented on src/plugins/laya-la-scmc/edit.vue
> +              @click="$bvModal.show('confirm-change-tf')"
Modal shows, but if you click "cancel", the variation is still changed and you have uneditable input fields

2023-01-20 10:48 UTC, cmauf commented on src/plugins/laya-la-scmc/create.vue
> +      } if (this.variation === this.single || this.variation === this.multiple) {
either insert `else` keyword or move `if` statement to new line

2023-01-20 10:48 UTC, cmauf commented on src/i18n/en.json
> +	"ok": "Ok",
`courseCreate.modal.ok` serves the purpose of a generic ok

2023-01-24 13:01 UTC, cmauf approved these changes
ok

2023-01-24 13:08 UTC, merged